module.exports = {
    '1-UP Studio': 'Nintendo',
    '2K Marin': '2K Games',
    '3 Minute Games, LLC': '3 Minute Games',
    'Acclaim Studios Manchester': 'Acclaim',
    'Acclaim Studios Salt Lake City': 'Acclaim',
    'AlphaDream Corporation, Ltd.': 'AlphaDream',
    'ASCII Corporation': 'ASCII',
    'Athena Co., Ltd.': 'Athena',
    'Atlus Co., Ltd.': 'Atlus',
    'Bethesda Game Studios': 'Bethesda',
    'Blizzard Entertainment': 'Blizzard',
    'Camelot Software Planning': 'Camelot',
    'cavia inc.': 'Cavia',
    'CING, Inc.': 'CING',
    'Crystal Dynamics, Inc.': 'Crystal Dynamics',
    'Dimps Corporation': 'Dimps',
    'DONTNOD Entertainment': 'DONTNOD',
    'EA Los Angeles': 'Electronic Arts',
    'EA Montreal': 'Electronic Arts',
    'Eidos-Montréal': 'Eidos',
    'Eurocom Entertainment Software': 'Eurocom',
    'Flagship Co., Ltd.': 'Flagship',
    'Fountainhead Entertainment, Inc.': 'Fountainhead',
    'Frontier Developments Ltd.': 'Frontier',
    'Game Freak, Inc.': 'Game Freak',
    'Gameloft S.A.': 'Gameloft',
    'Gearbox Software LLC': 'Gearbox',
    'Grasshopper Manufacture inc.': 'Grasshopper',
    'HAL Laboratory, Inc.': 'HAL Laboratory',
    'Harmonix Music Systems, Inc.': 'Harmonix',
    'Hudson Entertainment, Inc.': 'Hudson',
    'Human Entertainment, Inc.': 'Human Entertainment',
    'Human Head Studios, Inc.': 'Human Head',
    'iNiS Corp.': 'iNiS',
    'Intelligent Systems Co., Ltd.': 'Intelligent Systems',
    'Insomniac Games': 'Insomniac',
    'Inti Creates Co., Ltd.': 'Inti Creates',
    'Klei Entertainment Inc.': 'Klei',
    'Konami Computer Entertainment Osaka Co., Ltd.': 'Konami',
    'Konami Computer Entertainment Japan, Inc.': 'Konami',
    'Konami Computer Entertainment Tokyo': 'Konami',
    'Level-5 Inc.': 'Level-5',
    'Mistwalker Corporation': 'Mistwalker',
    'Monolith Productions, Inc.': 'Monolith Productions',
    'Monolith Software, Inc.': 'Monolith Soft',
    'n-Space, Inc.': 'n-Space',
    'Naughty Dog, Inc.': 'Naughty Dog',
    'Neverland Co., Ltd.': 'Neverland',
    'Neversoft Entertainment': 'Neversoft',
    'Nintendo EAD': 'Nintendo',
    'Nintendo EAD Tokyo Group No.1': 'Nintendo',
    'Nintendo EAD Tokyo Group No.2': 'Nintendo',
    'Nintendo EPD': 'Nintendo',
    'Nintendo R&D1': 'Nintendo',
    'Nintendo R&D3': 'Nintendo',
    'Now Production Co., Ltd.': 'Now Production',
    'Number None Inc': 'Number None',
    'Obsidian Entertainment': 'Obsidian',
    'Pandemic Studios': 'Pandemic',
    'Paon Corporation, Ltd.': 'Paon',
    'PopCap Games, Inc.': 'PopCap Games',
    'Quintet Co., Ltd.': 'Quintet',
    'Racjin Co., Ltd.': 'Racjin',
    'Rare, Ltd.': 'Rare',
    'RedLynx Ltd': 'RedLynx',
    'Remedy Entertainment Ltd.': 'Remedy',
    'Rockstar North': 'Rockstar',
    'Rockstar San Diego': 'Rockstar',
    'Rocksteady Studios Ltd': 'Rocksteady',
    'Silicon Knights, Inc.': 'Silicon Knights',
    'Sproing Interactive Media GmbH': 'Sproing',
    'SRD Co. Ltd.': 'Nintendo',
    'Sumo Digital Ltd.': 'Sumo Digital',
    'Taito Corporation': 'Taito',
    'Techland Sp. z o.o.': 'Techland',
    'Traveller\'s Tales Ltd.': 'Traveller\'s Tales',
    'tri-Crescendo Inc.': 'tri-Crescendo',
    'Ubisoft Montpellier Studios': 'Ubisoft',
    'Ubisoft Montreal Studios': 'Ubisoft',
    'Ubisoft Paris Studios': 'Ubisoft',
    'Ubisoft Shanghai Studios': 'Ubisoft',
    'Valve Corporation': 'Valve',
    'Vanillaware Ltd.': 'Vanillaware',
    'WayForward Technologies': 'WayForward',
    'Westwood Studios, Inc.': 'Westwood',
    'YAGER Development GmbH': 'Yager Development',
};
