fragment GameFields on Game {
    _id
    system {
        _id
        name
        order
    }
    title
    rating
    genre
    release
    developer
    description
    youTubeId
    compilation
    dlcs {
        title
        rating
    }
}
